# Project Name
TARGET = Blink

# Sources
CPP_SOURCES = Delay.cpp 

# Library Locations
LIBDAISY_DIR = deps/libDaisy
DAISYSP_DIR = deps/DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

